FROM java:8-jdk-alpine
MAINTAINER javaonfly
COPY ./target/adidas-product-creation-service-registry-0.0.1-SNAPSHOT.jar adidas-product-creation-service-registry-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","adidas-product-creation-service-registry-0.0.1-SNAPSHOT.jar" ]
CMD ["-jar", "adidas-product-creation-service-registry-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761